config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'about' => 'ebooks#about', :as => 'about'
  get 'contact' => 'ebooks#contact', :as => 'contact'
  get 'bookmark' => 'ebooks#bookmark', :as => 'bookmark'


	match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
	match 'auth/failure', to: redirect('/'), via: [:get, :post]
	match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
	
  get 'sessions/create'

  get 'sessions/destroy'

  resources :ebooks, only: [:index, :new, :create, :destroy, :show] do
    resources :pages
  end
  root "welcome#index"
end

app/models/ebook.rb
class Ebook < ActiveRecord::Base
	mount_uploader :attachment, AttachmentUploader
	belongs_to :user
	has_many :pages, dependent: :destroy
	validates :title, presence: true
	validates :attachment, presence: true,
		:file_size => { :maximum => 25.megabytes.to_i }
end

app/models/page.rb
class Page < ActiveRecord::Base
	belongs_to :ebook
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :ebooks
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
	  def current_user
	    @current_user ||= User.find(session[:user_id]) if session[:user_id]
	  end
	  helper_method :current_user
end

app/controllers/ebooks_controller.rb
class EbooksController < ApplicationController
  def index
    if current_user
      @ebooks = current_user.ebooks
      @title = "Home"
    else
      redirect_to root_path
    end
    @ebook = Ebook.new
  end

  def show
    @ebook = Ebook.find(params[:id])
    @pages = @ebook.pages.order("created_at ASC").paginate(:page => params[:page], :per_page => 1)
    if params[:page]
      @ebook.update_attribute(:bookmark, params[:page])
    end
    @bookmark = @ebook.bookmark
    render 'show'
  end

  def create
    @current_user = current_user
    title = EPUB::Parser.parse(params[:ebook][:attachment].path).metadata.title

    params[:ebook][:title] = title
  	@ebook = @current_user.ebooks.create(ebook_params)
    if @ebook.save
        Resque.enqueue(EbookUploader, @ebook.id, ENV['PUSHER_APP_ID'], ENV['PUSHER_KEY'], ENV['PUSHER_SECRET'])
        redirect_to ebook_path(@ebook)
    else
        render "create"
    end
  end

  def destroy
    @current_user = current_user
    @ebook = Ebook.find(params[:id])
    dir = "public/uploads/ebooks/#{@ebook.user.name.to_s.tr(' ', '_')}/#{@ebook.title.tr(' ', '_')}"

    s3 = AWS::S3.new
    bucket_name = ENV['S3_BUCKET_NAME']
    s3.buckets[bucket_name].objects.with_prefix(dir).delete_all # delete directory contents
    s3.buckets[bucket_name].objects.delete(dir) # delete directory

    @ebook.destroy
    redirect_to ebooks_path, notice: "'#{@ebook.title}' deleted!"
  end

  def about
    @title = "About"
    render "about"
  end

  def contact
    @title = "Contact"
    render "contact"
  end

	private
   	 def ebook_params
    	  params.require(:ebook).permit(:title, :attachment)
   	 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	if current_user
  		redirect_to ebooks_path
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ebooks_helper.rb
module EbooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ebooks/_spritz.html.erb
<script type="text/javascript">
	(function() {
		var spritzController = null;

		var onSpritzifySuccess = function(spritzText) {
			spritzController.startSpritzing(spritzText);
		};

		var onSpritzifyError = function(error) {
			alert("Unable to Spritz: " + error.message);
		};

		function onStartSpritzClick(event) {
			var text = $('#inputText').val();
			var locale = "en_us;";

			// Send to SpritzEngine to translate
			SpritzClient.spritzify(text, locale, onSpritzifySuccess, onSpritzifyError);
		};

		// Customized options
		var customOptions = {
	            placeholderText:    { startText: '' },
				redicleWidth: 	    434,	// Specify Redicle width
				redicleHeight: 	    76		// Specify Redicle height
		};

		var init = function() {
			$("#startSpritz").on("click", onStartSpritzClick);

			// Construct a SpritzController passing the customization options
			spritzController = new SPRITZ.spritzinc.SpritzerController(customOptions);

			// Attach the controller's container to this page's "spritzer" container
			spritzController.attach($("#spritzer"));

			var text = $('#inputText').val();
			var locale = "en_us;";

			// Send to SpritzEngine to translate
			SpritzClient.spritzify(text, locale, onSpritzifySuccess, onSpritzifyError);
			};

			$(document).ready(function() {
				init();
			});

	})();
</script>
			

app/views/ebooks/about.html.erb
<div class="jumbotron">
	<h1 align="middle">Blitz</h1>
	<p>
		Blitz (formally EZPub) is an online tool, PoweredbySpritz™, designed to help you read your eBooks faster, easier, and more effectively. In order to read at higher speeds, you must first register by clicking the "Login" link at the top right corner of the Spritz Redicle™.
		<br />
		This app was strongly inspired by <strong><a href="http://www.spritzinc.com/">Spritz</a></strong> and <strong><a href="http://www.readsy.co/">Readsy</a></strong>.
	</p>
	<p align="middle">
		Fork me on <a href="https://github.com/hyperbit/blitz">GitHub</a>.
	</p>
	<h1 align="middle">About the Developer</h1>
	<p>
		My name is <a href="http://www.jcano.me">Justin Cano</a> and I am a recent graduate from the University of California, Riverside with a BS in Computer Engineering. I am currently in process of searching for a full time Software Engineering position in the San Francisco Bay Area. If you would like to work with me or have any other inquiries, feel free to <%= link_to "contact me", contact_path %>.
	</p>

</div>

app/views/ebooks/contact.html.erb
<div class="jumbotron">
	<div align="middle">
		<p>
			<h1>Contact</h1>
			<ul class="list-unstyled">
				<li>Justin Cano</li>
		  		<li><a href="http://www.jcano.me">Website</a></li>
		  		<li><a href="http://blog.jcano.me">Blog</a></li>
		  		<li><a href="http://www.github.com/hyperbit">GitHub</a></li>
		  		<li><a href="https://portfolium.com/justincano">Portfolium</a></li>
		  		<li><a href="mailto:jcano001@ucr.edu">Email</a></li>
			</ul>
		</p>
	</div>
</div>

app/views/ebooks/create.html.erb
<h1>Invalid file! Must upload .epub</h1>
<%= link_to "Back", ebooks_path, class: "btn btn-primary" %>

app/views/ebooks/destroy.html.erb
<h1>Ebooks#destroy</h1>
<p>Find me in app/views/ebooks/destroy.html.erb</p>

app/views/ebooks/ebook.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />
<%= link_to "New Ebook", new_ebook_path, class: "btn btn-primary" %>
<br />
<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Download Link</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= @ebook.title %></td>
        <td><%= link_to "View Ebook", ebook_path(@ebook, :job_id => @job_id) %></td>
      </tr>
  </tbody>
</table>

app/views/ebooks/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />
<button class="btn btn-primary" data-toggle="modal" data-target="#myModal">Upload eBook <i class="fa fa-book"></i>
</button>
<br />
<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Download Link</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @ebooks.each do |ebook| %>
      <tr>
        <td><%= ebook.title %></td>
        <td><%= link_to "View Ebook", ebook_path(ebook) %></td>
        <td><%= button_to "Delete",  ebook, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{ebook.title}?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Select an eBook to read with Spritz</h4>
      </div>
      <div class="modal-body">
        <p style="color:#D95352;" align="middle">
          <strong>25 MB limit.</strong> Only .epub files allowed.
          <br/>
          Because eBooks are usually fairly large in size (>5 MB), it might take a while to upload and render. In addition, if your internet connection is slow, the app might timeout.
        </p>
        <%= form_for @ebook, html: { multipart: true } do |f| %>
          <%= f.file_field :attachment %>
          <%= f.submit "Upload", class: "btn btn-primary" %>
        <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </div>
  </div>
</div>

app/views/ebooks/show.html.erb
<%= javascript_tag do %>
	var pusher = new Pusher('c15372e0b28fbbc25e71');
	var channel = pusher.subscribe('ebook-uploader');

	pusher.log = function(message) {
	  if (window.console && window.console.log) {
	    window.console.log(message);
	  }
	};

	$(document).ready(function(){
		$('.progress').hide();
	});

	channel.bind('ebook-percent', function(data) {
		if (data.message != "done") {
			$('.progress').show()
			$('.progress-bar').css("width", data.message + "%");
		} else {
			window.location = window.location + '#loaded';
        	window.location.reload();
		}
	});

	window.onload = function() {
	    if(window.location.hash) {
	        pusher.disconnect();
	    }
	}
<% end %>
<% if @bookmark %>
	<%= javascript_tag do %>
		pusher.disconnect();
		var url = window.location.href;
		if (url.indexOf('?') == -1){  
			url += '?page=<%= @bookmark %>';
			window.location.href = url;
		}
	<% end %>
<% end %>
<div class="row">
	<div class="col-md-6">
		<%= link_to raw("<i class='fa fa-arrow-circle-o-left'></i>
 Back"), ebooks_path, class: "btn btn-primary" %>
	</div>
</div>
<div id="paginate" class="row" align="middle" data-toggle="tooltip" data-placement="top" title="Browse through different pages!">
	<%= will_paginate @pages, renderer: BootstrapPagination::Rails %>
</div>
<div class="row">
	<div class="col-md-6" align="middle">
		<br />
		<div id="spritzer" align="middle"></div>
		<br />
		<br />
		<button class="btn btn-success" id="startSpritz" type="submit" data-toggle="tooltip" data-placement="top" title="Click to Spritz through the page!">Spritz!</button>
		<br />
		<br />
		<textarea id="inputText" style="width:450px;height:250px;" data-toggle="tooltip" data-placement="right" title="Text-only contents of the eBook will be displayed here. Edit the text to be Spritz'd!">
			<%= render @pages %>
		</textarea>
	</div>
	<div id="ebook" class="col-md-6" data-placement="top" title="View contents of the eBook">
		<div class="progress">
		  <div class="progress-bar" role="progressbar" aria-valuemin="0" aria-valuemax="100">
		  </div>
		</div>
		<p>
			<%= render :partial => 'pages/content', :collection => @pages, :as => :page %>
		</p>
		<br />
	</div>
</div>
<div class="row" align="middle">
	<%= will_paginate @pages, renderer: BootstrapPagination::Rails %>
</div>


<%= render 'spritz' %>
<script>
      $('#paginate').tooltip()
      $('#startSpritz').tooltip()
      $('#inputText').tooltip()
      $('#ebook').tooltip()
</script>

app/views/layouts/_footer.html.erb
	</div>

	<hr>
	<div align="middle">
		© 2014 <a href="http://www.github.com/hyperbit">hyperbit</a>.
	</div>

	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-54475839-1', 'auto');
	  ga('send', 'pageview');

	</script>
</body>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blitz</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<script type="text/javascript">
		var SpritzSettings = {
			clientId: "4524122930975538943",
			redirectUri: "http://read-blitz.herokuapp.com/login_success.html",
		};
	</script>
	<script type="text/javascript" src="//sdk.spritzinc.com/js/1.2/js/spritz.min.js"></script>
  <script src="//js.pusher.com/2.2/pusher.min.js"></script>
  <%= csrf_meta_tags %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
  <!-- Facebook Like Button -->
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=271696996369711&version=v2.0";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

	<!-- Navbar -->
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Blitz", root_path, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
        <% end %>
        <li<% if @title == "Home" %> class="active" <% end %>><%= link_to "Home", ebooks_path %></li>
        <li<% if @title == "About" %> class="active" <% end %>><%= link_to "About", about_path %></li>
        <li<% if @title == "Contact" %> class="active" <% end %>><%= link_to "Contact", contact_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

	<div class="container" style="padding-top:20px;">

app/views/layouts/application.html.erb
<%= render 'layouts/header' %>
		<%= yield %>
<%= render 'layouts/footer' %>

app/views/pages/_content.html.erb
<iframe id="frame" width="100%" height="850" src="<%= page.path %>">
  <p>Your browser does not support iframes.</p>
</iframe>

app/views/pages/_page.html.erb
<%= strip_tags(sanitize(strip_links(page.content))) %>

app/views/welcome/index.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <h1>Blitz <small>PoweredbySpritz™</small></h1>
  <p>Blitz (formally EZPub) is an online tool designed to help you read your eBooks faster, easier, and more effectively by using the power of <strong><a href="http://www.spritzinc.com/">Spritz</a></strong>.</p>
  <p>
    <%= link_to raw("<i class='fa fa-facebook'></i>
 | Sign in with Facebook"), "/auth/facebook", id: "sign_in", class: "btn btn-primary btn-lg" %>
    <br />
    <a id="why" data-toggle="tooltip" data-placement="top" title="We use Facebook Authentication as a simple way to keep track of the books you upload. We promise we don't ever post anything or share your personal info :)" style="font-size:0.5em;">why?</a>
  </p>
</div>

<div class="row">
  <div align="middle">
    <div class="well">
      <div class="fb-like" data-href="https://read-blitz.herokuapp.com/" data-layout="standard" data-action="like" data-show-faces="false" data-share="true"></div>
    </div>
  </div>
</div>

<hr>

<div>
  <h1>Screenshots</h1>
  <br />
  <h2>Book Cover</h2>
  <br />
  <div align="middle">
    <%= image_tag("screenshot1.jpg", :alt => "Front Page", :width => "75%") %>
  </div>
  <br />
  <h2>Spritz'ing eBook Content</h2>
  <div align="middle">
    <%= image_tag("screenshot2.jpg", :alt => "Spritz", :width => "75%") %>
  </div>
  <em>Book: <strong>The Next America</strong> by Paul Taylor</em>
</div>

<script>
  $('#why').tooltip()
</script>